package tests;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;

import calc.StringCalculator;

public class StringCalculatorTest {
	
	private StringCalculator calc;
	
	@Before
	public void setup(){
		calc = new StringCalculator();
	}

	@Test
	public void returnOne() throws Exception {
		assertEquals(1, calc.add("1"));
	}
	
	@Test
	public void returnTwo() throws Exception {
		assertEquals(2, calc.add("2"));
	}
	
	@Test
	public void returnZeroForEmptyString() throws Exception {
		assertEquals(0, calc.add(""));
	}
	
	@Test
	public void returnSumOfTwoNumbers() throws Exception {
		assertEquals(3, calc.add("1,2"));
	}
	
	@Test
	public void returnSumOfThreeNumbers() throws Exception {
		assertEquals(6, calc.add("1,2,3"));
	}
	
	@Test
	public void returnSumOfNumbersWithStringContainingNewLine() throws Exception {
		assertEquals(6, calc.add("1\n2,3"));
	}
	
	@Test
	public void testAddWithCustomDelimiter() throws Exception {		
		assertEquals(6, calc.add("//;\n1;2;3"));
	}
	
	@Test(expected = Exception.class)
	public void negativeNumberThrowsException() throws Exception {
		calc.add("1,-2");
	}
	
	
	
	
}
